### ISSUE TITLE
赛马和背单词这两个插件在3.0版本出现了问题

### ISSUE THREAD

**Issue by sakurasep** [MadokaProject/Madoka#43]
升级之后无法使用
![Snipaste_2022-07-17_17-41-47](https://user-images.githubusercontent.com/70024132/179392717-18cf96d7-8a42-4df8-ad2a-9af381b4de65.jpg)

**Comment by Colsrch** [comment]
> 升级之后无法使用
> ![Snipaste_2022-07-17_17-41-47](https://user-images.githubusercontent.com/70024132/179392717-18cf96d7-8a42-4df8-ad2a-9af381b4de65.jpg)
> 

将下列目录删除后重新启动。
```
app​/​plugin​/​extension​/
app/tmp/mcserver
```
扩展插件需重新安装

**Comment by Colsrch** [comment]
请尝试升级madoka并更新相关插件
