### ISSUE TITLE
【反馈】：app/util/control.py 开头的链接似乎失效了

### ISSUE THREAD

**Issue by zyckk4** [MadokaProject/Madoka#71]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经将 Madoka 升级到最新版本。

### 复现步骤

app/util/control.py 开头的链接 https://github.com/McZoo/Xenon/blob/master/lib/control.py 似乎失效了

**Comment by Colsrch** [comment]
您好，这是借鉴的人家的代码，文件开头标注了来源。无法访问可能是人家闭源或者删库了
